// Vue-Cli/src/App.vue
<template>
    <h1 class="title">hello app</h1>
    <el-button type="primary">按钮</el-button>
    <ul>
        <li><router-link to="/home">home</router-link></li>
        <li><router-link to="about">about</router-link></li>
    </ul>
    <router-view />
</template>

<script>
    import { ElButton } from "element-plus";
    
    export default {
        name: "App",
    }
</script>

<style>
    .title {
        color: blue;
    }
</style>

// React-Cli/src/App.jsx
import React, { Suspense, lazy } from "react";
import { Link, Routes, Route } from 'react-router-dom';
import { Button } from "antd";
// import Home from './pages/Home';
// import About from './pages/About';

const Home= lazy(() => import(/* webpackChunkName: 'pages-home' */"./pages/Home"));
const About= lazy(() => import(/* webpackChunkName: 'pages-about' */"./pages/About"));

function App() {
    return (
        <div>
            <h1>App</h1>
            <Button type="primary">按钮</Button>
            <ul>
                <li><Link to="/home">Home</Link></li>
                <li><Link to="/about">About</Link></li>
            </ul>
            
            <Suspense>
                <Routes>
                    <Route path="/home" element={<Home />} />
                    <Route path="/about" element={<About />} />
                </Routes>
            </Suspense>
        </div>
        
    )
}

export default App;
